routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/vue', function () {
    return view('welcome');
});


Route::get('/home','PostsController@index');
//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
Route::get('/offers','PostsController@offers');
Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');
Route::get('/foodgraphy','PostsController@foodgraphy');


Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');


Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});

//Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ReviewsController.php
<?php

namespace App\Http\Controllers;

use App\reviews;
use Illuminate\Http\Request;
use App\restaurant;


class ReviewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = reviews::all();
        return view('reviews.index')->withreviews($reviews);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
  $x = restaurant::all();


        return view("reviews.create")->withx($x);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\reviews  $reviews
     * @return \Illuminate\Http\Response
     */
    public function show(reviews $reviews)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\reviews  $reviews
     * @return \Illuminate\Http\Response
     */
    public function edit(reviews $reviews)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\reviews  $reviews
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, reviews $reviews)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\reviews  $reviews
     * @return \Illuminate\Http\Response
     */
    public function destroy(reviews $reviews)
    {
        //
    }
}

resources/views/reviews/create.blade.php
@extends('main_admin')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Create New Restaurant</h1>
            <hr>
            <form method="POST" action="{{ route('reviews.store') }}">
                <div class="form-group">
                    <label name="restaurant_name">Restaurant name:</label>
                    <select name="restaurant_name" id="restaurant_name" class="form-control">
                        <option value=""> -- Select One --</option>
                        @foreach ($x as $restaurant_name)
                            <option value="{{ $restaurant_name->id }}">{{ $restaurant_name->restaurant_name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label name="restaurant_name">Place:</label>
                    <input id="restaurant_name" name="restaurant_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="restaurant_name">Name of food:</label>
                    <input id="restaurant_name" name="restaurant_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="restaurant_name">rating:</label>
                    <input id="restaurant_name" name="restaurant_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="address">comment:</label>
                    <textarea id="address" name="address" rows="10" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                    <small id="fileHelp" class="form-text text-muted"></small>
                </div>
                <input type="submit" value="give review" class="btn btn-success btn-lg btn-block">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </form>
        </div>
    </div>﻿

    @endsection

resources/views/reviews/edit.blade.php
@extends('main_admin')

@section('content')

    <form method="POST" action="{{ route('restaurant.update', $restaurant->id) }}">
        <div class="form-group">
            <label for="restaurant_name">restaurant_name:</label>
            <textarea type="text" class="form-control input-lg" id="restaurant_name" name="restaurant_name" rows="1" style="resize:none;">{{ $restaurant->restaurant_name }}</textarea>
        </div>
        <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
        {{ method_field('PUT') }}

                    </div>
                </div>
            </div>
        </div>

    </form>﻿
    @endsection

resources/views/reviews/index.blade.php
@extends('main')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>all post</h1>

       </div>
        <div class="col-md-2">

            <a href="{{ route('reviews.create') }}" class="btn btn-primary btn-block">Give a review</a>

        </div>

<div class="row">
    <div class="col-md-12">
        <table class="table">

            <thead>
            <th>#</th>
            <th>restaurant name</th>
            <th>address</th>
            <th>created at</th>

            </thead>
<tbody>
  @foreach($reviews as $review)
<tr>
    <th>{{$review->id}}</th>
    <td>{{$rreview->restaurant_name}}</td>
    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection

resources/views/reviews/show.blade.php
@extends('main_admin')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$restaurant->restaurant_name}}</h1>
            <p class="form-control">{{$restaurant->address}} </p>
        </div>
    </div>﻿


        <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
             {{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿







    @endsection