routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/vue', function () {
    return view('welcome');
});


Route::get('/home','PostsController@index');
//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
Route::get('/offers','PostsController@offers');
Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');
Route::get('/foodgraphy','PostsController@foodgraphy');


Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');


Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});

//Route::get('/home', 'HomeController@index')->name('home');

app/restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class restaurant extends Model
{
    //
}

app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use App\restaurant;
use Illuminate\Http\Request;

class RestaurantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        //
        $restaurants = restaurant::all();
        return view('restaurant.index')->withrestaurants($restaurants);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

return view('restaurant.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $restaurant = new restaurant;
        $restaurant->restaurant_name =$request->restaurant_name;
        $restaurant->address =$request->address;


        $restaurant->save();
        return redirect()->route('restaurant.show',$restaurant->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
     $restaurant = restaurant::find($id);
     return view('restaurant.show')->withrestaurant($restaurant);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $restaurant = restaurant::find($id);
        return view('restaurant.edit')->withrestaurant($restaurant);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $restaurant = restaurant::find($id);
        $restaurant->restaurant_name= $request->input('restaurant_name');
        $restaurant->address= $request->input('address');
        $restaurant->save();
        return redirect()->route('restaurant.show',$restaurant->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $restaurant = restaurant::find($id);
        $restaurant->delete();
        return redirect()->route('restaurant.index');


    }
}

resources/views/restaurant/create.blade.php
@extends('main_admin')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Create New Restaurant</h1>
            <hr>
            <form method="POST" action="{{ route('restaurant.store') }}">
                <div class="form-group">
                    <label name="restaurant_name">Restaurant name:</label>
                    <input id="restaurant_name" name="restaurant_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="address">Address:</label>
                    <textarea id="address" name="address" rows="10" class="form-control"></textarea>
                </div>
                <input type="submit" value="Create Post" class="btn btn-success btn-lg btn-block">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </form>
        </div>
    </div>﻿

    @endsection

resources/views/restaurant/edit.blade.php
@extends('main_admin')

@section('content')

    <form method="POST" action="{{ route('restaurant.update', $restaurant->id) }}">
        <div class="form-group">
            <label for="restaurant_name">restaurant_name:</label>
            <textarea type="text" class="form-control input-lg" id="restaurant_name" name="restaurant_name" rows="1" style="resize:none;">{{ $restaurant->restaurant_name }}</textarea>
        </div>
        <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
        {{ method_field('PUT') }}

                    </div>
                </div>
            </div>
        </div>

    </form>﻿
    @endsection

resources/views/restaurant/index.blade.php
@extends('main_admin')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>all post</h1>

       </div>
        <div class="col-md-2">

            <a href="{{ route('restaurant.create') }}" class="btn btn-primary btn-block">create restaurant</a>

        </div>

<div class="row">
    <div class="col-md-12">
        <table class="table">

            <thead>
            <th>#</th>
            <th>restaurant name</th>
            <th>address</th>
            <th>created at</th>

            </thead>
<tbody>
  @foreach($restaurants as $restaurant)
<tr>
    <th>{{$restaurant->id}}</th>
    <td>{{$restaurant->restaurant_name}}</td>
    <td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                {{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection

resources/views/restaurant/show.blade.php
@extends('main_admin')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$restaurant->restaurant_name}}</h1>
            <p class="form-control">{{$restaurant->address}} </p>
        </div>
    </div>﻿


        <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
             {{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿







    @endsection