routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/vue', function () {
    return view('welcome');
});


Route::get('/home','PostsController@index');
//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
Route::get('/offers','PostsController@offers');
Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');
Route::get('/foodgraphy','PostsController@foodgraphy');


Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');


Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/foodgraphy.blade.php
@extends('main')
@section('content')
    <div class="row">
        <div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h1 class="gallery-title">Gallery</h1>
        </div>

        <div align="center">
            <button class="btn btn-default filter-button" data-filter="all">All</button>
            <button class="btn btn-default filter-button" data-filter="indian">indian</button>
            <button class="btn btn-default filter-button" data-filter="deshi">deshi</button>
            <button class="btn btn-default filter-button" data-filter="chinese">chinese</button>

        </div>
        <br/>



        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter indian">
            <img src="{{URL::asset('/images/aa.jpg')}}" alt="profile Pic" height="300" width="300 " class="img-responsive">
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter indian">
            <img src="{{URL::asset('/images/ss.jpg')}}" alt="profile Pic" height="365" width="365" class="img-responsive">
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter deshi">
            <img src="{{URL::asset('/images/dd.jpg')}}" alt="profile Pic" height="365" width="365" class="img-responsive">
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter deshi">
            <img src="{{URL::asset('/images/ff.jpg')}}" alt="profile Pic" height="365" width="365" class="img-responsive">
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter chinese">
            <img src="{{URL::asset('/images/gg.jpg')}}" alt="profile Pic" height="365" width="365" class="img-responsive">
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter chinese">
            <img src="{{URL::asset('/images/hh.jpg')}}" alt="profile Pic" height="365" width="365" class="img-responsive">
        </div>


    </div>
    @endsection

resources/views/pages/home.blade.php
@extends('main')
@section('content')

        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1 class="text-center" id="aa">What are you looking for</h1>
                    <div class="form-group">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-group" id="adv-search">
                                        <input type="text" class="form-control" placeholder="Search restaurant,reviews" />
                                        <div class="input-group-btn">
                                            <div class="btn-group" role="group">
                                                <div class="dropdown dropdown-lg">
                                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                                                    <div class="dropdown-menu dropdown-menu-right" role="menu">
                                                        <form class="form-horizontal" role="form">
                                                            <div class="form-group">
                                                                <label for="filter">search by</label>
                                                                <select class="form-control">

                                                                    <option value="1">restaurant</option>
                                                                    <option value="2">review</option>

                                                                </select>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="contain">Place</label>
                                                                <input class="form-control" type="text" />
                                                            </div>

                                                            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                                                        </form>
                                                    </div>
                                                </div>
                                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
        <div class="container">

        <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Trending Foods</h1></div>
        <div class="col-md-4">
            <div class="thumbnail"> <img src="{{URL::asset('/images/food.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                <div class="caption">
                    <h3>pizza</h3>
                </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
        </div>
            <div class="col-md-4">
                <div class="thumbnail"> <img src="{{URL::asset('/images/gg.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                    <div class="caption">
                        <h3>Gamblers mix</h3>
                    </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail"> <img src="{{URL::asset('/images/rr.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                    <div class="caption">
                        <h3>Special Swarma</h3>
                    </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
            </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Trending Places</h1></div>
        <div class="col-md-4">
            <div class="thumbnail"> <img src="{{URL::asset('/images/32.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                <div class="caption">
                    <h3>Sky view</h3>
                </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail"> <img src="{{URL::asset('/images/44.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                <div class="caption">
                    <h3>Amari</h3>
                </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail"> <img src="{{URL::asset('/images/3.jpg')}}" alt="profile Pic" height="200" width="200 " class="img-responsive">
                <div class="caption">
                    <h3>Royal Buffet</h3>
                </div><a class="btn btn-primary btn-block" role="button" href="#">Button</a></div>
        </div>

        </div>
    </div>
</div>

    @endsection

resources/views/pages/offers.blade.php
@extends('main')
@section('content')

    <form>
        <p id="offerspara">Find Offers</p>
        <select class="form-control">
            <optgroup label="Search By">
                <option value="12" selected="">Location</option>
                <option value="13">Price</option>
            </optgroup>
        </select>



        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Restaurant</th>
                    <th>Offer name</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Pasta State</td>
                    <td>Buy one get one</td>
                </tr>
                <tr>
                    <td>Cafe Entro</td>

                    <td>Happy hour</td>
                </tr>
                </tbody>
            </table>
        </div>
    </form>

    @endsection

resources/views/pages/review.blade.php
@extends('main')
@section('content')

    <h1 class="text-center text-warning">Reviews</h1>

    <div class="container" >
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
            <a href="/reviews/create" class="btn btn-info" role="button">Write a review</a>
            </div>

            </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <table class="table">

                <thead>
                <th>reviewer</th>
                <th>restaurant name</th>
                <th>item name</th>
                <th>rating</th>
                <th>review</th>

                </thead>
                <tbody>

                  <td>ayon</td>
                  <td>kfc</td>
                  <td>chicken</td>
                  <td>6</td>
                  <td>average</td>


                </tbody>
                <tbody>

                <td>smita</td>
                <td>bfc</td>
                <td>coleslaw</td>
                <td>8</td>
                <td>good</td>


                </tbody>
                <tbody>

                <td>hridima</td>
                <td>tune&bites</td>
                <td>jazz lovers meal</td>
                <td>9</td>
                <td>very good</td>


                </tbody>
            </table>


        </div>

    </div>
    {{--<div class="container" >
        <div class="text-center">
        <a href="/write_a_review" class="btn btn-info" role="button">Write a review</a>  </div>  </div>
--}}
    @endsection

resources/views/pages/share_a_food.blade.php
@extends('main')
@section('content')


    <h1 class="text-center text-danger">Share A Food</h1></div>
    <div class="container">
        <form method="POST" action="{{ route('shareafood.store') }}">
            {{ csrf_field() }}




            <div class="form-group">
                <label name="restaurant_name">Restaurant name:</label>
                <input id="restaurant_name" name="restaurant_name" class="form-control">
            </div>
            <div class="form-group">
                <label name="address">Address:</label>
                <input id="address" name="address" rows="10" class="form-control"></input>
            </div>

            <input type="submit" value="Create Post" class="btn btn-success btn-lg btn-block">
            <input type="hidden" name="_token" value="{{ Session::token() }}">
            </div>
    </form>


    @endsection

resources/views/pages/write_a_review.blade.php
@extends('main')
@section('content')

    <form>

        <div class="form-group">
            <label for="exampleSelect1">Restaurant</label>
                <select class="form-control" id="exampleSelect1">
                    <option>BFC</option>
                    <option>Sub Lovers</option>
                    <option>Pizza Inn</option>
                    <option>Chillox</option>
                    <option>CP</option>
                </select>
        </div>
        <div class="form-group">
            <label for="exampleSelect1">name of food</label>
            <select class="form-control" id="exampleSelect1">
                <option>Sub Sandwich</option>
                <option>Pasta Bssta</option>
                <option>Pizza</option>
                <option>Burger</option>
                <option>Chicken Nuggets</option>
            </select>
        </div>
        <div class="form-group">
            <label for="exampleSelect1">Rating</label>
            <select class="form-control" id="exampleSelect1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </div>

        <div class="form-group">
            <label for="exampleTextarea">comments</label>
            <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputFile">File input</label>
            <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
            <small id="fileHelp" class="form-text text-muted"></small>
        </div>

        <div  class="text-center">
        <button type="submit"   class="btn btn-primary">Submit</button>
        </div>
    </form>

@endsection